Running ant (compile)...................................................... OK
Running ant (compile.tests)................................................ OK
mkdir: cannot create directory ‘lib/’: File exists
cp: cannot stat ‘/home/tdurieux/defects4j/framework/projects/Closure/lib/*’: No such file or directory
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:97)
	at xxl.java.junit.TestSuiteExecution.runTestCase(TestSuiteExecution.java:36)
	at xxl.java.junit.TestSuiteExecution.runTestCases(TestSuiteExecution.java:81)
	at fr.inria.lille.repair.nopol.synth.ConstraintModelBuilder.buildFor(ConstraintModelBuilder.java:82)
	at fr.inria.lille.repair.nopol.synth.DefaultSynthesizer.buildPatch(DefaultSynthesizer.java:67)
	at fr.inria.lille.repair.nopol.NoPol.solveWithMultipleBuild(NoPol.java:185)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:119)
	at fr.inria.lille.repair.nopol.NoPol.build(NoPol.java:89)
	at fr.inria.lille.repair.nopol.NoPolLauncher.launch(NoPolLauncher.java:84)
	at fr.inria.lille.repair.Main.main(Main.java:61)
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:201)
	at xxl.java.junit.TestSuiteExecution.executionResult(TestSuiteExecution.java:90)
	... 9 more

real	41m43.664s
user	175m43.968s
sys	0m14.276s
